# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [366]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

In [0]:
import numpy as np
import pandas as pd

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X= iris.data
y=iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=42)

In [372]:
y_train.shape

(112,)

In [373]:
y_train

array([0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0,
       0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
       2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0,
       1, 2])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [375]:
print(y_train.shape)

(112, 3)


In [376]:
y_train[:2]

array([[1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3,input_shape=(4,), activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [380]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [381]:
model.fit(X_train,y_train, validation_data=(X_test, y_test), epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 2.7156 - accuracy: 0.3125 - val_loss: 1.7098 - val_accuracy: 0.3947
Epoch 2/100
112/112 [==============================] - 0s 227us/sample - loss: 1.6294 - accuracy: 0.2857 - val_loss: 1.3382 - val_accuracy: 0.1842
Epoch 3/100
112/112 [==============================] - 0s 232us/sample - loss: 1.3191 - accuracy: 0.1607 - val_loss: 1.2425 - val_accuracy: 0.2368
Epoch 4/100
112/112 [==============================] - 0s 219us/sample - loss: 1.2241 - accuracy: 0.2857 - val_loss: 1.1908 - val_accuracy: 0.1842
Epoch 5/100
112/112 [==============================] - 0s 238us/sample - loss: 1.1777 - accuracy: 0.2500 - val_loss: 1.1524 - val_accuracy: 0.2105
Epoch 6/100
112/112 [==============================] - 0s 214us/sample - loss: 1.1346 - accuracy: 0.2679 - val_loss: 1.1165 - val_accuracy: 0.2368
Epoch 7/100
112/112 [==============================] - 0s 222us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_predict=model.predict(X_test[:3])

In [383]:
y_predict[:3]

array([[0.06132346, 0.5898395 , 0.348837  ],
       [0.8763371 , 0.08446127, 0.03920166],
       [0.0029739 , 0.52896696, 0.46805912]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [384]:
print(y_test[:3])

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [386]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [0]:
import pandas as pd
price=pd.read_csv("prices.csv")

In [390]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104090 entries, 0 to 104089
Data columns (total 7 columns):
date      104090 non-null object
symbol    104090 non-null object
open      104090 non-null float64
close     104090 non-null float64
low       104090 non-null float64
high      104090 non-null float64
volume    104089 non-null float64
dtypes: float64(5), object(2)
memory usage: 5.6+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
price=price.drop(["date","symbol"],axis=1)

In [392]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104090 entries, 0 to 104089
Data columns (total 5 columns):
open      104090 non-null float64
close     104090 non-null float64
low       104090 non-null float64
high      104090 non-null float64
volume    104089 non-null float64
dtypes: float64(5)
memory usage: 4.0 MB


In [393]:
price.shape

(104090, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
price=price[:1000]

In [395]:
price.shape

(1000, 5)

In [396]:
price.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X=price.drop(["volume"],axis=1)
y=price["volume"] / 1000000

In [398]:
y.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

In [399]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X=X.to_numpy().astype('float32')
y=y.to_numpy().astype('float32')

In [401]:
print(X.shape)
print(y.shape)

(1000, 4)
(1000,)


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X = tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(X, W, b):
    y_pred = tf.add(tf.matmul(X, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def train(x, y_actual, W, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([W,b])
        current_prediction = prediction(x, W, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[W, b])
    
    # Update Weights and Bias
    W = W - learning_rate * dw
    b = b - learning_rate * db
    
    return W, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [407]:
for i in range(100):    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [408]:
W.numpy()

array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [409]:
b.numpy()

array([4.607657], dtype=float32)